plugins:
  - jemoji
  - jekyll-titles-from-headings
  - premonition
  - jekyll-spaceship

markdown: CommonMarkGhPages
  
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
